from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
import random
app = FastAPI()

piadas = [
    "Por que o livro de matemática se suicidou? Porque tinha muitos problemas.",
    "O que o zero disse para o oito? Belo cinto!",
    "Por que o computador foi ao médico? Porque pegou um vírus.",
    "O que o tomate foi fazer no banco? Tirar extrato.",
    "Por que a vaca foi para o espaço? Para ver o vácuo.",
    "O que é um pontinho verde na esquina? Uma ervilha de castigo.",
    "Por que o lápis estava triste? Porque perdeu a ponta.",
    "O que o café disse para o açúcar? Você me adoça!",
    "Por que o espantalho ganhou prêmio? Porque era destaque na área.",
    "O que o peixe disse quando bateu na parede? Dam!",
    "Por que o calendário foi promovido? Porque tinha muitos encontros.",
    "O que a impressora falou para a outra? Essa folha é sua ou é impressão minha?",
    "Por que o relógio foi ao psicólogo? Estava passando por uma fase difícil.",
    "O que o pão disse para o outro? A vida é um miolo.",
    "Por que a bateria foi presa? Porque cometeu um crime.",
    "O que o gelo disse para a água? Somos muito frios.",
    "Por que o cachorro sentou na sombra? Porque estava quente-cão.",
    "O que a lâmpada falou? Estou iluminada!",
    "Por que o celular foi para a academia? Para ficar mais conectado.",
    "O que o papel disse para a caneta? Para de me pressionar!",
    "Por que o sapato brigou? Porque estava apertado.",
    "O que o vento falou? Estou de passagem.",
    "Por que o gato entrou no computador? Para mexer no mouse.",
    "O que a nuvem disse? Estou nas alturas.",
    "Por que a cadeira não trabalha? Porque vive encostada.",
    "O que o milho falou? Estou pipocando de alegria.",
    "Por que o espelho não mente? Porque reflete.",
    "O que o martelo disse? Estou pregado.",
    "Por que o sorvete foi ao dentista? Porque tinha frio nos dentes.",
    "O que o relógio falou? Estou atrasado!",
    "Por que a laranja foi promovida? Porque era uma fruta de talento.",
    "O que o gelo falou no verão? Estou derretendo de emoção.",
    "Por que o peixe não usa computador? Porque tem medo da rede.",
    "O que a banana disse? Estou descascando de rir.",
    "Por que o lápis não gosta de futebol? Porque sempre é cortado.",
    "O que o livro falou? Tenho muitas histórias.",
    "Por que o café foi ao terapeuta? Porque estava expresso demais.",
    "O que o chinelo disse? Estou de saco cheio.",
    "Por que o avião não conta segredo? Porque sempre voa longe.",
    "O que o feijão disse? Estou cheio de gás.",
    "Por que o computador ficou feliz? Porque recebeu um upgrade.",
    "O que a formiga falou? Trabalho duro.",
    "Por que o gelo não discute? Porque esfria a cabeça.",
    "O que o poste disse? Estou iluminando ideias.",
    "Por que o tomate ficou vermelho? Porque viu a salada nua.",
    "O que o foguete falou? Estou nas nuvens!",
    "Por que o caderno ficou bravo? Porque rasgaram suas páginas.",
    "O que o sapo disse? Estou pulando de alegria.",
    "Por que o músico foi preso? Porque cometeu um acorde errado.",
    "O que o cachorro falou? Au-torizado!",
    "Por que a galinha atravessou a rua? Para chegar do outro lado.",
    "O que o elevador falou? Estou subindo na vida.",
    "Por que o gelo foi demitido? Porque não era quente no trabalho.",
    "O que o livro de história disse? Já vi isso antes.",
    "Por que o tomate não corre? Porque é molenga.",
    "O que o raio disse? Que choque!",
    "Por que o café não dorme? Porque está sempre ligado.",
    "O que a porta disse? Estou aberta a novas ideias.",
    "Por que o leite se escondeu? Porque viu o gato.",
    "O que o teclado falou? Estou sem espaço.",
    "Por que o feijão não vai à festa? Porque dá gás.",
    "O que o celular falou? Estou sem bateria social.",
    "Por que o gelo virou água? Porque perdeu a cabeça.",
    "O que o chapéu disse? Vou na sua cabeça.",
    "Por que o peixe é rico? Porque vive cheio de escamas.",
    "O que o ônibus falou? Estou lotado de emoções.",
    "Por que o cego não briga? Porque não vê motivo.",
    "O que o espelho falou? Sou reflexivo.",
    "Por que o lápis foi ao médico? Porque estava sem ponta.",
    "O que o cachorro disse? Estou au-sente.",
    "Por que o papel ficou com vergonha? Porque foi amassado.",
    "O que o gato falou? Estou miando de rir.",
    "Por que o tomate foi ao médico? Porque estava pelado.",
    "O que o foguete disse? Vou decolar dessa situação.",
    "Por que o computador não bebe café? Porque já tem bytes.",
    "O que o sol falou? Estou brilhando hoje.",
    "Por que o gelo não faz amigos? Porque é frio demais.",
    "O que a abelha disse? Estou zumbindo de alegria.",
    "Por que o livro não gosta de chuva? Porque molha a história.",
    "O que o relógio disse? Hora de rir.",
    "Por que o peixe não gosta de basquete? Porque tem medo da rede.",
    "O que o copo disse? Estou cheio de mim.",
    "Por que o bolo foi ao médico? Porque estava queimado.",
    "O que a estrela disse? Estou brilhando na vida.",
    "Por que o vento não trabalha? Porque vive à toa.",
    "O que o cavalo disse? Estou relinchando de rir.",
    "Por que o gelo não corre? Porque escorrega.",
    "O que o microfone disse? Estou amplificando a piada.",
    "Por que o cachorro é bom músico? Porque tem bom faro musical.",
    "O que a lua disse? Estou cheia hoje.",
    "Por que o lápis não mente? Porque aponta a verdade.",
    "O que o tomate falou? Estou amassado.",
    "Por que o café terminou o namoro? Porque foi passado para trás.",
    "O que o carro disse? Estou sem freio nas risadas.",
    "Por que o gato não usa Facebook? Porque já tem nove vidas.",
    "O que o gelo falou? Estou em estado sólido.",
    "Por que o pão não conta segredo? Porque abre o bico.",
    "O que o ventilador disse? Estou girando de felicidade.",
    "Por que o celular não briga? Porque evita conflito de conexão.",
    "O que o espantalho disse? Estou palhaçando."
]

@app.get("/")
def puxarIndex():
    return FileResponse("templates/index.html")

def sorteio(piadas):
    piada = random.choice(piadas)
    return piadas
